# Generated by Django 5.2 on 2025-04-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='level',
            field=models.CharField(choices=[('college', 'College Level'), ('intercollege', 'Inter-College'), ('national', 'National'), ('international', 'International'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch of Study'),
        ),
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='College/University'),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for_team',
            field=models.BooleanField(default=False, verbose_name='Actively looking for team members'),
        ),
    ]
